# -*- coding: utf-8 -*-
"""4. Label Encoding Linear Regression.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ywDB_o1EPXM-f9MzqHa9ZMR3CY_4fYpe
"""

import numpy as np
import pandas as pd
import seaborn as sns
from sklearn import linear_model
import warnings
warnings.filterwarnings("ignore")

"""**Read data**"""

# Uploaded from C:\Users\wel51x\Box\MyBox\Data\Housing Data
df = pd.read_csv("train.csv")
#df

print(df.KitchenQual.value_counts())
#[0 if df.KitchenQual[i] == "Fa" else 1 if df.KitchenQual[i] == "TA" else 2 if df.KitchenQual[i] == "Gd" else 3 for i in range(len(df))]
sns.barplot(data=df, x="KitchenQual", y="SalePrice")

"""**Clean and encode**"""

df = df[["KitchenQual", "SalePrice"]]
df

X = pd.DataFrame()
# Transform KitchenQual Fa, TA, Gd, rest(Ex) to 0, 1, 2, 3
X["KitchenQual"] = [0 if df.KitchenQual[i] == "Fa" else 1 if df.KitchenQual[i] == "TA" else 2 if df.KitchenQual[i] == "Gd" else 3 for i in range(len(df))]

y = df.SalePrice
#print(X.KitchenQual.value_counts())
#X

"""**Define model type and fit**"""

# Step 1: define model
lm = linear_model.LinearRegression()

# Step 2: fit X to Y
lm.fit(X, y)

"""**Results**"""

print("coeff = ", lm.coef_, "intercept = ", lm.intercept_)

KitchenQual = ["Fa", "TA", "Gd", "Ex"]
for i in range(4):
  print("For Kitchen Quality =", KitchenQual[i], "==> Sale Price prediction is", lm.predict([[i]]))